stages:
    - test
    - build
    - deploy

run_unit_tests:
    stage: test   
    before_script:
        - echo "Preparing test data ..." 
    script:
        - echo "Running Unit tests ..."
    after_script:
        - echo "Cleaning cache..."

run_lint_tests:
    stage: test   
    before_script:
        - echo "Preparing test data ..." 
    script:
        - echo "Running lintt tests ..."
    after_script:
        - echo "Cleaning cache..."         

build_image:
    stage: build
    script:
        - echo "Building image..."
        - echo "tagging the docker image.."

push_image:
    stage: build
    needs:
        - build_image
    script:
        - echo "pushing the docker image..."

deploy_image:
    stage: deploy
    script:
        - echo "Deploying image to dev server..."
